apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus
  namespace: monitoring
  labels:
    app.kubernetes.io/type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"