apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  namespace: nirmal
  labels:
    app.kubernetes.io/type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"